ComputerStore/ComputerStore.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ComputerStore.Domain.Entities;
using ComputerStore.Domain.Abstract;
using ComputerStore.WebUI.Models;

namespace ComputerStore.WebUI.Controllers
{
    public class CartController : Controller
    {


        private IComputerComponentRepository repository;
        private IOrderProcessor orderProcessor;
        public CartController(IComputerComponentRepository repo, IOrderProcessor processor)
        {
            repository = repo;
            orderProcessor = processor;
        }
        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }
        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry,your cart is empty!");
            }

            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }
        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToRouteResult AddToCart(Cart cart, int computercomponentId, string returnUrl)
        {
            ComputerComponent component = repository.ComputerComponents
                .FirstOrDefault(g => g.ComputerComponentId == computercomponentId);

            if (component != null)
            {
                cart.AddItem(component, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int computercomponentId, string returnUrl)
        {
            ComputerComponent component = repository.ComputerComponents
                .FirstOrDefault(g => g.ComputerComponentId == computercomponentId);

            if (component != null)
            {
                cart.RemoveLine(component);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }
       
    }
}

ComputerStore/ComputerStore.WebUI/Controllers/ComputerComponentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ComputerStore.Domain.Abstract;
using ComputerStore.Domain.Entities;
using ComputerStore.WebUI.Models;


namespace ComputerStore.WebUI.Controllers
{
    public class ComputerComponentController : Controller
    {
        private IComputerComponentRepository repository;
        public int pageSize = 4;
        public ComputerComponentController(IComputerComponentRepository repo)
        {
            repository = repo;
        }
        public ViewResult List(string category,int page = 1)
        {
            ComponentListViewModel model = new ComponentListViewModel
            {
                ComputerComponents = repository.ComputerComponents
            .Where(p => category == null || p.Category == category)
            .OrderBy(component => component.ComputerComponentId)
            .Skip((page - 1) * pageSize)
            .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ?
                    repository.ComputerComponents.Count():
                    repository.ComputerComponents.Where(component=>component.Category==category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }
        public FileContentResult GetImage(int computercomponentId)
        {
            ComputerComponent computercomponent = repository.ComputerComponents
                .FirstOrDefault(g => g.ComputerComponentId == computercomponentId);

            if (computercomponent != null)
            {
                return File(computercomponent.ImageData, computercomponent.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

ComputerStore/ComputerStore.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ComputerStore.Domain.Abstract;

namespace ComputerStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IComputerComponentRepository repository;
        public NavController(IComputerComponentRepository repo)
        {
            repository = repo;
        }
        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = repository.ComputerComponents
                .Select(component => component.Category)
                .Distinct()
                .OrderBy(x => x);
           
            return PartialView("FlexibleMenu",categories);
        }
    }
}

ComputerStore/ComputerStore.WebUI/Views/Shared/ComputerComponentSummary.Mobile.cshtml
@model ComputerStore.Domain.Entities.ComputerComponent

<div data-role="collapsible" data-collapsed="false" data-content-theme="c">
    <h2>@Model.Name</h2>
    <div>
        <div>
            @Model.Description
        </div>
        <div>
            <strong>(@Model.Price.ToString("# zl"))</strong>
        </div>
        <div>
            @using (Html.BeginForm("AddToCart", "Cart"))
            {
                @Html.HiddenFor(x => x.ComputerComponentId)
                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                <input type="submit" class="btn btn-success" value="To Cart" />
            }
        </div>
    </div>
</div>

ComputerStore/ComputerStore.WebUI/Views/Shared/ComputerComponentSummary.cshtml
@model ComputerStore.Domain.Entities.ComputerComponent

<div class="well">
    @if (Model.ImageData != null)
    {
        <div class="pull-left" style="margin-right: 10px">
            <img class="img-thumbnail" width="75" height="75"
                 src="@Url.Action("GetImage", "ComputerComponent",
                new { Model.ComputerComponentId })" />
        </div>
    }
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("# zl")</span>
    </h3>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.ComputerComponentId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add to Cart" />
        </div>
    }
    <span class="lead">@Model.Description</span>
</div>

ComputerStore/ComputerStore.WebUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.9.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title></title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

ComputerStore/ComputerStore.WebUI/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"
          href="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css" />
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div data-role="page" id="page1">
        <div data-theme="a" data-role="header" data-position="fixed">
            <h3>ComputerStore</h3>
            @Html.Action("Menu", "Nav")
        </div>
        <div data-role="content">
            <ul data-role="listview" data-divider-theme="b" data-inset="false">
                @RenderBody()
            </ul>
        </div>
    </div>
</body>
</html>

ComputerStore/ComputerStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<style>
    .navbar-right{
        float:right!important;
        margin-right:15px;
        margin-left:15px;
    }
</style>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">
        <span class="hidden-xs">ComputerStore - computer parts store</span>
            <div class="visible-xs">Computer</div>
            <div class="visible-xs">Store</div>
        </a>
        @Html.Action("Summary", "Cart")
    </div>
    <div class="visible-xs">
        @Html.Action("Menu","Nav",new { horizontalNav = true})
    </div>
    <div class="row panel">
        <div id="categories" class="col-sm-3 hidden-xs">
            @Html.Action("Menu","Nav")
        </div>
        <div class="col-xs-12 col-sm-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>