ComputerStore/ComputerStore.WebUI/Controllers/AdminController.cs
using System.Web.Mvc;
using ComputerStore.Domain.Abstract;
using ComputerStore.Domain.Entities;
using System.Linq;
using System.Web;

namespace ComputerStore.WebUI.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        IComputerComponentRepository repository;

        public AdminController(IComputerComponentRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index()
        {
            return View(repository.ComputerComponents);
        }

        public ViewResult Edit(int computercomponentId)
        {
            ComputerComponent computercomponent = repository.ComputerComponents
                .FirstOrDefault(g => g.ComputerComponentId == computercomponentId);
            return View(computercomponent);
        }

        [HttpPost]
        public ActionResult Edit(ComputerComponent computercomponent, HttpPostedFileBase image = null)
        {
            if (ModelState.IsValid)
            {
                if(image != null)
                {
                    computercomponent.ImageMimeType = image.ContentType;
                    computercomponent.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(computercomponent.ImageData, 0, image.ContentLength);
                }
                repository.SaveProduct(computercomponent);
                TempData["message"] = string.Format("Changes in product \"{0}\" were saved", computercomponent.Name);
                return RedirectToAction("Index");
            }
            else
            {
                // Smth wrong with data
                return View(computercomponent);
            }
        }

        public ViewResult Create()
        {
            return View("Edit", new ComputerComponent());
        }

        [HttpPost]
        public ActionResult DeleteProduct(int computercomponentId)
        {
            ComputerComponent deletedProduct = repository.DeleteProduct(computercomponentId);
            if (deletedProduct != null)
            {
                TempData["message"] = string.Format("Product \"{0}\" was deleted",
                    deletedProduct.Name);
            }
            return RedirectToAction("Index");
        }
    }
}

ComputerStore/ComputerStore.WebUI/Controllers/ComputerComponentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ComputerStore.Domain.Abstract;
using ComputerStore.Domain.Entities;
using ComputerStore.WebUI.Models;


namespace ComputerStore.WebUI.Controllers
{
    public class ComputerComponentController : Controller
    {
        private IComputerComponentRepository repository;
        public int pageSize = 4;
        public ComputerComponentController(IComputerComponentRepository repo)
        {
            repository = repo;
        }
        public ViewResult List(string category,int page = 1)
        {
            ComponentListViewModel model = new ComponentListViewModel
            {
                ComputerComponents = repository.ComputerComponents
            .Where(p => category == null || p.Category == category)
            .OrderBy(component => component.ComputerComponentId)
            .Skip((page - 1) * pageSize)
            .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ?
                    repository.ComputerComponents.Count():
                    repository.ComputerComponents.Where(component=>component.Category==category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }
        public FileContentResult GetImage(int computercomponentId)
        {
            ComputerComponent computercomponent = repository.ComputerComponents
                .FirstOrDefault(g => g.ComputerComponentId == computercomponentId);

            if (computercomponent != null)
            {
                return File(computercomponent.ImageData, computercomponent.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

ComputerStore/ComputerStore.WebUI/Views/Admin/Edit.cshtml
@model ComputerStore.Domain.Entities.ComputerComponent

@{
    ViewBag.Title = "Admin panel: editing a product";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel">
    <div class="panel-heading">
        <h3>Editing products «@Model.Name»</h3>
    </div>

    @using (Html.BeginForm("Edit", "Admin",FormMethod.Post,new {enctype="multipart/form-data" }))
    {
        <div class="panel-body">
            @Html.HiddenFor(m => m.ComputerComponentId)
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                switch (property.PropertyName)
                {
                    case "ComputerComponentId":
                    case "ImageData":
                    case "ImageMimeType":
                        // do nothing
                        break;
                    default:
                        <div class="form-group">
                            <label>@(property.DisplayName ?? property.PropertyName)</label>
                            @if (property.PropertyName == "Description")
                            {
                                @Html.TextArea(property.PropertyName, null,
                                    new { @class = "form-control", rows = 5 })
                            }
                            else
                            {
                                @Html.TextBox(property.PropertyName, null,
                                    new { @class = "form-control" })
                            }
                            @Html.ValidationMessage(property.PropertyName)
                        </div>
                        break;
                }
            }
            <div class="form-group">
                <div style="position:relative;">
                    <label>Image</label>
                    <a class='btn' href='javascript:;'>
                        Choose a file...
                        <input type="file" name="Image" size="40"
                               style="position:absolute;z-index:2;top:0;
                                left:0;filter: alpha(opacity=0); opacity:0;
                                background-color:transparent;color:transparent;"
                               onchange='$("#upload-file-info").html($(this).val());'>
                    </a>
                    <span class='label label-info' id="upload-file-info"></span>
                </div>
                @if (Model.ImageData == null)
                {
                    <div class="form-control-static">Without image</div>
                }
                else
                {
                    <img class="img-thumbnail" width="150" height="150"
                         src="@Url.Action("GetImage", "ComputerComponent",
                        new { Model.ComputerComponentId })" />
                }
            </div>
        </div>
        <div class="panel-footer">
            <input type="submit" value="Save" class="btn btn-primary" />
            @Html.ActionLink("Discard changes and return to the list", "Index", null, new
            {
                @class = "btn btn-default"
            })
        </div>
    }
</div>

ComputerStore/ComputerStore.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<ComputerStore.Domain.Entities.ComputerComponent>

@{
    ViewBag.Title = "Admin Panel";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>List of computer components</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-right">ID</th>
                <th>Name</th>
                <th class="text-right">Price</th>
                <th class="text-center">Action</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-right">@item.ComputerComponentId</td>
                    <td>@Html.ActionLink(item.Name, "Edit", new { item.ComputerComponentId })</td>
                    <td class="text-right">@item.Price.ToString("# zl")</td>
                    <td class="text-center">
                        @using (Html.BeginForm("Delete", "Admin"))
                        {
                            @Html.Hidden("ComputerComponentIdId", item.ComputerComponentId)
                            <input type="submit"
                                   class="btn btn-default btn-xs"
                                   value="Delete" />
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Add a Component", "Create", null,
            new { @class = "btn btn-default" })
    </div>
</div>